#!/usr/bin/env bash
cd `dirname $0`

source virtualenvwrapper.sh

# virtualenvwrapper doesn't work with "set -e
function check_worked {
    if ! $*
    then
        exit 1
    fi
}

workon pubsubpull_1.4
cd test-projects/django_1_4
echo Django 1.4
check_worked python -tt manage.py test pubsubpull

workon pubsubpull_1.7
cd ../django_1_7
echo Django 1.7
check_worked python manage.py test pubsubpull

workon pubsubpull_1.0
cd ../django_1_0
echo Django 1.0
check_worked python manage.py test d1
